"""empty message

Revision ID: b9999e045b9d
Revises: 7ff092df7efe
Create Date: 2017-08-16 21:25:39.684549

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = 'b9999e045b9d'
down_revision = '7ff092df7efe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contests', sa.Column('rules', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contests', 'rules')
    # ### end Alembic commands ###
